Update linting tasks

diff --git a/.github/workflows/manifests-validation.yaml b/.github/workflows/manifests-validation.yaml
--- a/.github/workflows/manifests-validation.yaml
+++ b/.github/workflows/manifests-validation.yaml
@@ -11,7 +11,7 @@ jobs:
   kustomize-lint:
     runs-on: ubuntu-latest
     env:
-      KUSTOMIZE_VERSION: 3.9.4
+      KUSTOMIZE_VERSION: 4.5.7
     steps:
       - name: Install Kustomize
         run: |
@@ -37,3 +37,37 @@ jobs:
           pip install yamllint
       - name: Validate Manifests
         run: yamllint . -f github
+  helm-lint:
+    runs-on: ubuntu-latest
+    env:
+      HELM_VERSION: 3.9.4
+      HELM_DIRS: .
+    steps:
+      - name: Install Helm
+        run: |
+          sudo curl -L -o /usr/bin/helm https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
+          sudo chmod +x /usr/bin/helm
+      - name: Code Checkout
+        uses: actions/checkout@v2
+      - name: Validate Charts
+        run: |
+          for i in `find "${HELM_DIRS}" -name "Chart.yaml" -exec dirname {} \;`;
+          do
+
+            echo
+            echo "Validating $i"
+            echo
+
+            helm lint $i
+
+            build_response=$?
+
+            if [ $build_response -ne 0 ]; then
+              echo "Error linting $i"
+              exit 1
+            fi
+
+          done
+
+          echo
+          echo "Charts successfully validated!"
